parameters:
#    kmc_kmc.example.class: Kmc\Bundle\KmcBundle\Example

services:
#    kmc_kmc.example:
#        class: %kmc_kmc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kmc_kmc.imageloader:
        class: Kmc\Bundle\KmcBundle\Utils\ImageLoader
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]