imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/Kmc/Bundle/UserBundle/Resources/Views": KmcUserBundle    

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Kmc\Bundle\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    use_flash_notifications: true
    from_email:
        address: mathieu.pisonero@gmail.com
        sender_name: mathieu
    registration:
        form:
             type: Kmc\Bundle\UserBundle\Form\RegistrationType
    profile:
        form:
             type: Kmc\Bundle\UserBundle\Form\ProfileType
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/uploadfile', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/token', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        jquery_file_upload:
            inputs:
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.iframe-transport.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-process.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-image.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-audio.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-video.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-validate.js'
                - '@KmcAdminBundle/Resources/public/plugins/form/jquery-file-upload/js/jquery.fileupload-ui.js'
        jquery_and_ui:
           inputs:
               - '@KmcAdminBundle/Resources/public/plugins/jquery/jquery-1.9.1.min.js'
               - '@KmcAdminBundle/Resources/public/plugins/jquery/jquery-migrate-1.1.0.min.js'
               - '@KmcAdminBundle/Resources/public/plugins/jquery/jquery.validate.min.js'
               - '@KmcAdminBundle/Resources/public/plugins/jquery/jquery.validate.config.js'
               - '@KmcAdminBundle/Resources/public/plugins/jquery-ui/ui/minified/jquery-ui.min.js'
               - '@KmcAdminBundle/Resources/public/plugins/scrollbar/slimscroll/jquery.slimscroll.min.js'
        base:
           inputs:
               - '@KmcAdminBundle/Resources/public/plugins/cookie/js/js.cookie.js'
               - '@KmcAdminBundle/Resources/public/plugins/bootstrap/js/bootstrap.min.js'
