# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Kmc\Bundle\UserBundle\Entity\User: sha512
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username
        auth_token_user_provider:
            id: auth_token_user_provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~
        main_login:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: kmc_admin_homepage
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                handlers: [kmc.logoutlistener] 
            remember_me:
                secret:     %secret%
    access_control:
        - { path: ^/admin, roles: ROLE_USER }