# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    kmcuserbundle.form.registration:
        class: Kmc\Bundle\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: kmc_user_registration }
    kmcuserbundle.form.profil:
        class: Kmc\Bundle\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: kmc_user_profile }